"""Writes lib/anton-metrics.ts: Anton's advance widths, for sizing card text without a font.

Dev-only and run by hand (the output is committed):  python3 scripts/anton-metrics.py

Cards are SVG images that name Anton but never embed it (GitHub's camo proxy serves them as
images, which cannot load fonts), so a viewer without Anton gets Impact or Arial Black. The
card measures each string with Anton's metrics and pins it with textLength, so whatever face
renders is squeezed to the same box and nothing overflows.
"""

import json
from pathlib import Path

from fontTools.ttLib import TTFont

HERE = Path(__file__).resolve().parent.parent
FONT = TTFont(str(HERE / "public/fonts/Anton.ttf"))
UPM = FONT["head"].unitsPerEm
CMAP = FONT.getBestCmap()
HMTX = FONT["hmtx"]

CHARS = "".join(chr(c) for c in range(32, 127)) + "×—–…·"
widths = {}
for ch in CHARS:
    g = CMAP.get(ord(ch))
    if g is None:
        continue
    widths[ch] = round(HMTX[g][0] / UPM, 4)

body = ", ".join(f"{json.dumps(k)}: {v}" for k, v in widths.items())
fallback = round(sum(widths.values()) / len(widths), 4)
out = f"""// Generated by scripts/anton-metrics.py from public/fonts/Anton.ttf. Do not edit by hand.
// Advance widths in em. Anton is uppercase-heavy but lowercase is measured too.

export const ANTON_ADVANCE: Record<string, number> = {{ {body} }};

export const ANTON_FALLBACK = {fallback};
"""
(HERE / "lib/anton-metrics.ts").write_text(out)
print(f"{len(widths)} glyphs, upm {UPM}")
