"""Outlines the TOKENMAXXING wordmark from public/fonts/Anton.ttf into lib/wordmark-paths.ts.

Dev-only and run by hand after a wordmark change (the output is committed, so the site never
needs Python or fontTools):  python3 scripts/wordmark-paths.py

Units: Anton's cap height is 100. Glyphs are slanted 10 degrees about the last baseline, the
same italic lean as jobmaxxing.ai's wordmark; the component adds the -6 degree tilt.
"""

import math
from pathlib import Path

from fontTools.pens.recordingPen import RecordingPen
from fontTools.pens.svgPathPen import SVGPathPen
from fontTools.pens.transformPen import TransformPen
from fontTools.ttLib import TTFont

HERE = Path(__file__).resolve().parent.parent
FONT = TTFont(str(HERE / "public/fonts/Anton.ttf"))
CAP = FONT["OS/2"].sCapHeight
CMAP = FONT.getBestCmap()
GLYPHS = FONT.getGlyphSet()
HMTX = FONT["hmtx"]
LEAN = math.tan(math.radians(10))
TRACK = 2.0  # extra units between letters; the keyline stroke bridges the gap anyway


class Line:
    def __init__(self, text: str, size: float, x0: float, base: float, ref: float):
        self.text, self.size, self.x0, self.base, self.ref = text, size, x0, base, ref
        self.s = size / CAP

    def advances(self):
        x = self.x0
        for ch in self.text:
            name = CMAP[ord(ch)]
            yield ch, name, x
            x += HMTX[name][0] * self.s + TRACK * self.size / 100

    @property
    def width(self) -> float:
        *_, (ch, name, x) = self.advances()
        return x + HMTX[name][0] * self.s - self.x0

    def lean(self, y: float) -> float:
        return LEAN * (self.ref - y)

    def draw(self, pen) -> None:
        s = self.s
        for _, name, x in self.advances():
            # font (fx, fy) -> svg: X = x + s*fx + LEAN*(ref - (base - s*fy)), Y = base - s*fy
            m = (s, 0, LEAN * s, -s, x + LEAN * (self.ref - self.base), self.base)
            GLYPHS[name].draw(TransformPen(pen, m))

    def x_of(self, index: int) -> float:
        return list(self.advances())[index][2]


def path(*lines: Line) -> str:
    pen = SVGPathPen(GLYPHS, ntos=lambda v: f"{v:.1f}".rstrip("0").rstrip("."))
    for line in lines:
        line.draw(pen)
    return pen.getCommands()


# Each layout says how far it tilts: the stack leans like jobmaxxing's, the one-line header
# mark leans less so it stays short.
EXTRUDE = (10, 17)  # the candy extrusion, down and right, in cap-100 units
KEYLINE = 17  # the white die-cut keyline's stroke width


def points(*lines: Line):
    rec = RecordingPen()
    for line in lines:
        line.draw(rec)
    return [pt for _, args in rec.value for pt in args]


def layout(name: str, rows: list[str], tilt: float, gap: float = 12, fyi_size: float = 44):
    ref = 100 + (len(rows) - 1) * (100 + gap)
    lines = [Line(t, 100, 0, 100 + i * (100 + gap), ref) for i, t in enumerate(rows)]
    last = lines[-1]
    fyi = Line(".fyi", fyi_size, last.width + 6, last.base, ref)
    letters, dot = path(*lines), path(fyi)

    # the drawn box, after extrusion, keyline and the tilt, so the viewBox is tight
    pts = points(*lines, fyi)
    pad = KEYLINE / 2 + 4
    xs0 = [x for x, _ in pts]
    ys0 = [y for _, y in pts]
    cx, cy = (min(xs0) + max(xs0)) / 2, (min(ys0) + max(ys0)) / 2
    a = math.radians(tilt)
    out = []
    for x, y in pts:
        for ex, ey in ((0, 0), EXTRUDE):
            px, py = x + ex - cx, y + ey - cy
            out.append((cx + px * math.cos(a) - py * math.sin(a), cy + px * math.sin(a) + py * math.cos(a)))
    x0 = min(x for x, _ in out) - pad
    y0 = min(y for _, y in out) - pad
    x1 = max(x for x, _ in out) + pad
    y1 = max(y for _, y in out) + pad
    return {
        "name": name,
        "letters": letters,
        "fyi": dot,
        "viewBox": f"{x0:.1f} {y0:.1f} {x1 - x0:.1f} {y1 - y0:.1f}",
        "tilt": f"rotate({tilt} {cx:.1f} {cy:.1f})",
    }


def coin_t() -> str:
    """Anton's T for the coin mark: cap height 54, slanted like the wordmark, centred on (64, 64)."""
    size = 54
    t = Line("T", size, 0, 0, 0)
    w = HMTX[CMAP[ord("T")]][0] * t.s
    # centre the slanted glyph: its lean shifts the top right by LEAN * size, so split it
    t = Line("T", size, 64 - w / 2 - LEAN * size / 2, 64 + size / 2, 64 + size / 2)
    return path(t)


def main() -> None:
    out = [
        "// Generated by scripts/wordmark-paths.py from public/fonts/Anton.ttf. Do not edit by hand.",
        "// Units: cap height 100, glyphs already slanted. COIN_T is the favicon's letter, in a 128 box.",
        "",
    ]
    for spec in (layout("STACK", ["TOKEN", "MAXXING"], tilt=-6), layout("LINE", ["TOKENMAXXING"], tilt=-3)):
        n = spec["name"]
        out.append(f"export const WORDMARK_{n} = {{")
        for k in ("viewBox", "tilt"):
            out.append(f'  {k}: "{spec[k]}",')
        out.append(f'  letters: "{spec["letters"]}",')
        out.append(f'  fyi: "{spec["fyi"]}",')
        out.append("} as const;")
        out.append("")
    out.append(f'export const COIN_T = "{coin_t()}";')
    out.append("")
    (HERE / "lib/wordmark-paths.ts").write_text("\n".join(out))


if __name__ == "__main__":
    main()
